spring:
  datasource:
    driver-class-name: org.firebirdsql.jdbc.FBDriver
    useUnicode: true
    characterEncoding: UTF-8
    sql-script-encoding: UTF-8
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  security:
    user:
      password: Start123
